name: 02 - Build App and Deploy

on: 
  workflow_call:
    inputs:
      mode:
        description: 'Run mode'
        required: true
        type: string
        default: 'draft'
      has_changes:
        description: 'Indicates if there are changes to build'
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      mode:
        description: 'Run mode'
        required: true
        default: 'draft'
        type: choice
        options:
          - draft
          - release
      has_changes:
        description: 'Indicates if there are changes to build'
        required: false
        type: boolean
        default: false
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/02-build.yml
env:
  BASE_PATH: "./app"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ${{ env.BASE_PATH }}
        run: npm install

      - name: Build the application
        id: build-site
        working-directory: ${{ env.BASE_PATH }}
        env:
          BASE_URL: /${{ github.event.repository.name }}/
        run: |
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: astro-build
          path: ${{ env.BASE_PATH }}/dist/
          retention-days: 7
          
  deploy:
    if: inputs.mode == 'release' && inputs.has_changes
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: astro-build
          path: .

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4